version: '3'

services:
  database:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - volumen_mysql:/var/lib/mysql
      - ./backup.sh:/backup.sh
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD= ${DB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${DB_ROOT_PASSWORD}
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    tty: true
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - volumen_redis:/data
    networks:
      - backend
networks:
  backend:
    external:
      name: "${DOCKER_NETWORK}"

volumes:
  volumen_mysql:
  volumen_redis:
